import type { Product } from "../types";

export const SEED_PRODUCTS: Product[] = [
  { id: "P001", name: "Qalmi Dates", category: "Dates", hsnCode: "08041010", unit: "kg", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 20 },
  { id: "P002", name: "Zahidi Dates", category: "Dates", hsnCode: "08041010", unit: "kg", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 20 },
  { id: "P003", name: "Kimia Dates", category: "Dates", hsnCode: "08013210", unit: "kg", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 20 },
  { id: "P004", name: "Almond (Badam)", category: "Dry Fruits & Nuts", hsnCode: "08021200", unit: "kg", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 20 },
  { id: "P005", name: "Majdool Dates", category: "Dates", hsnCode: "08041010", unit: "kg", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 20 },
  { id: "P006", name: "Ajwa Dates", category: "Dates", hsnCode: "08041010", unit: "kg", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 20 },
  { id: "P007", name: "Fard Dates", category: "Dates", hsnCode: "08041010", unit: "kg", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 20 },
  { id: "P008", name: "Cashew (Kaju)-W320", category: "Dry Fruits & Nuts", hsnCode: "08013210", unit: "kg", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 20 },
  { id: "P009", name: "Cashew (Kaju)-W210", category: "Dry Fruits & Nuts", hsnCode: "08013210", unit: "kg", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 20 },
  { id: "P010", name: "Mehran Chicken Tikka", category: "Spices & Masalas", hsnCode: "09109100", unit: "pcs", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 20 },
  { id: "P011", name: "Mehran Biryani Masala", category: "Spices & Masalas", hsnCode: "09109100", unit: "pcs", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 20 },
  { id: "P012", name: "Mehran Hyderabadi Biryani", category: "Spices & Masalas", hsnCode: "09109100", unit: "pcs", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 20 },
  { id: "P013", name: "Mehran Bombay Biryani", category: "Spices & Masalas", hsnCode: "09109100", unit: "pcs", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 20 },
  { id: "P014", name: "Mehran Malai Biryani", category: "Spices & Masalas", hsnCode: "09109100", unit: "pcs", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 20 },
  { id: "P015", name: "Mehran Mutton Biryani", category: "Spices & Masalas", hsnCode: "09109100", unit: "pcs", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 20 },
  { id: "P016", name: "Mehran Tikka Boti Biryani", category: "Spices & Masalas", hsnCode: "09109100", unit: "pcs", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 20 },
  { id: "P017", name: "Mehran Tandoori Masala", category: "Spices & Masalas", hsnCode: "09109100", unit: "pcs", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 20 },
  { id: "P018", name: "Mehran Meat Masala", category: "Spices & Masalas", hsnCode: "09109100", unit: "pcs", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 20 },
  { id: "P019", name: "Mehran Sheek Kabab", category: "Spices & Masalas", hsnCode: "09109100", unit: "pcs", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 20 },
  { id: "P020", name: "Mehran Shami Kabab", category: "Spices & Masalas", hsnCode: "09109100", unit: "pcs", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 20 },
  { id: "P021", name: "Mehran Chicken Masala", category: "Spices & Masalas", hsnCode: "09109100", unit: "pcs", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 20 },
  { id: "P022", name: "Mehran Kheer Mix", category: "Desserts & Mixes", hsnCode: "21069099", unit: "pcs", gstRate: 18, unitPrice: 0, stockQty: 0, reorderLevel: 20 },
  { id: "P023", name: "Mehran Pista Kheer", category: "Desserts & Mixes", hsnCode: "21069099", unit: "pcs", gstRate: 18, unitPrice: 0, stockQty: 0, reorderLevel: 20 },
  { id: "P024", name: "Mehran Badam Kheer", category: "Desserts & Mixes", hsnCode: "21069099", unit: "pcs", gstRate: 18, unitPrice: 0, stockQty: 0, reorderLevel: 20 },
  { id: "P025", name: "Mehran Sheer Khorma", category: "Desserts & Mixes", hsnCode: "21069099", unit: "pcs", gstRate: 18, unitPrice: 0, stockQty: 0, reorderLevel: 20 },
  { id: "P026", name: "Mehran Fish Masala", category: "Spices & Masalas", hsnCode: "09109100", unit: "pcs", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 20 },
  { id: "P027", name: "Pistachios - Roasted", category: "Dry Fruits & Nuts", hsnCode: "20081920", unit: "kg", gstRate: 12, unitPrice: 0, stockQty: 0, reorderLevel: 10 },
  { id: "P028", name: "Anjeer (Dried Fig)", category: "Dry Fruits & Nuts", hsnCode: "08042010", unit: "kg", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 10 },
  { id: "P029", name: "Akhrot (Walnuts)", category: "Dry Fruits & Nuts", hsnCode: "08023200", unit: "kg", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 10 },
  { id: "P030", name: "Kismis (Raisins)", category: "Dry Fruits & Nuts", hsnCode: "08062010", unit: "kg", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 10 },
  { id: "P031", name: "Pumpkin Seeds", category: "Seeds", hsnCode: "08129090", unit: "kg", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 10 },
  { id: "P032", name: "Sunflower Seeds", category: "Seeds", hsnCode: "12060000", unit: "kg", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 10 },
  { id: "P033", name: "Chia Seeds", category: "Seeds", hsnCode: "12119099", unit: "kg", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 10 },
  { id: "P034", name: "Flax Seeds (Alsi)", category: "Seeds", hsnCode: "12040000", unit: "kg", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 10 },
  { id: "P035", name: "Sattu - 200g", category: "Flours & Grains", hsnCode: "11061090", unit: "kg", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 10 },
  { id: "P036", name: "Sattu - 500g", category: "Flours & Grains", hsnCode: "11061090", unit: "kg", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 10 },
  { id: "P037", name: "Besan - 200g", category: "Flours & Grains", hsnCode: "11061090", unit: "kg", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 10 },
  { id: "P038", name: "Besan - 500g", category: "Flours & Grains", hsnCode: "11061090", unit: "kg", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 10 },
  { id: "P039", name: "Besan - 24C Loose", category: "Flours & Grains", hsnCode: "11061090", unit: "kg", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 10 },
  { id: "P040", name: "Bajra Atta", category: "Flours & Grains", hsnCode: "10039000", unit: "kg", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 10 },
  { id: "P041", name: "Ragi Atta", category: "Flours & Grains", hsnCode: "10082130", unit: "kg", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 10 },
  { id: "P042", name: "Makka Atta", category: "Flours & Grains", hsnCode: "10059000", unit: "kg", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 10 },
  { id: "P043", name: "Multi Grain Atta", category: "Flours & Grains", hsnCode: "11010000", unit: "kg", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 10 },
  { id: "P044", name: "Chawal Atta", category: "Flours & Grains", hsnCode: "11029010", unit: "kg", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 10 },
  { id: "P045", name: "Jeera (Cumin Seeds)", category: "Spices & Masalas", hsnCode: "09093120", unit: "pcs", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 20 },
  { id: "P046", name: "Marich (Black Pepper)", category: "Spices & Masalas", hsnCode: "09041110", unit: "pcs", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 20 },
  { id: "P047", name: "Laung (Cloves)", category: "Spices & Masalas", hsnCode: "09071000", unit: "pcs", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 20 },
  { id: "P048", name: "Methi (Fenugreek Seeds)", category: "Spices & Masalas", hsnCode: "09109914", unit: "pcs", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 20 },
  { id: "P049", name: "Sauf (Fennel Seeds)", category: "Spices & Masalas", hsnCode: "09096139", unit: "pcs", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 20 },
  { id: "P050", name: "Badi Ilaichi (Large Cardamom)", category: "Spices & Masalas", hsnCode: "09083120", unit: "pcs", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 20 },
  { id: "P051", name: "Choti Ilaichi (Green Cardamom)", category: "Spices & Masalas", hsnCode: "09083110", unit: "pcs", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 20 },
  { id: "P052", name: "Daalchini (Cinnamon)", category: "Spices & Masalas", hsnCode: "09061100", unit: "pcs", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 20 },
  { id: "P053", name: "Jawitri (Mace)", category: "Spices & Masalas", hsnCode: "09082100", unit: "pcs", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 20 },
  { id: "P054", name: "Makhana (Foxnuts)", category: "Dry Fruits & Nuts", hsnCode: "04109020", unit: "pcs", gstRate: 5, unitPrice: 0, stockQty: 0, reorderLevel: 20 },
  { id: "P055", name: "Talbina Mix", category: "Desserts & Mixes", hsnCode: "21069099", unit: "pcs", gstRate: 18, unitPrice: 0, stockQty: 0, reorderLevel: 20 },
];
